### ISSUE TITLE
Add build automation for text embeddings backend

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai-backend-text-embeddings#4]
```[tasklist]
### Tasks
- [ ] Automate build for dev/latest docker images (on push to main)
- [ ] Automate build for release docker images (on tag)
- [ ] Automate build for Zarf packages (on tag)
```
